/** Stable model-facing operating discipline for the Team tool family. */
export const AGENT_SWARM_USAGE_PROMPT = `Use agent_swarm_* when the user requests a coordinated multi-agent Team.
1. Create one Team, then add role-specific continuable members.
2. Decompose the goal into tasks with explicit acceptance criteria and dependency ids. The event scheduler assigns ready tasks.
3. Compose workflows on the task DAG itself: serial stages are dependency chains (a stage's join is every dependent naming its blockers); fan out through dependency-free same-layer tasks only — actual concurrency is bounded by the member count and mailbox quotas, never around them; hand pipeline artifacts through task outputs and Team mail; put human decisions at the review transaction (a submission waiting for review IS the human gate); a task whose dependency has not completed stays held — never skip or auto-fail it.
4. Every task mutation uses the latest revision. Every worker submission also carries its exact attempt id; stale attempts stop immediately.
5. A worker submission is evidence, not completion. The captain must call agent_swarm_review_task to accept or reject it. When a task carries declared verification commands, an executable review Provider reruns them in an isolated review root and rejects on failure with root-produced evidence.
6. Persist peer messages before delivery. A queued result is durable; never resend it automatically. Prefer quiet for information the recipient should read on its next turn; quiet mail to an inactive member stays queued until a wakeup or its own return, and wakeup is the delivery that resumes it.
7. Treat write scopes as coordination hints, not filesystem authorization. Use agent_swarm_status for fixed Team counters, agent_swarm_list_tasks (status/owner/ready filters) for task rows, agent_swarm_list_memory (category/literal-content filters) for durable shared memory, and agent_swarm_list_members (phase filter) for durable member composition. The member reader reports recorded provider/model/preset and deny declarations only; it never exposes persona text, assigned Skills, or an effective tool-permission claim. All list tools use cursor pagination.
8. agent_swarm_interrupt_member is Host-evidence-gated: it succeeds only when the Host confirms that the member's current visible tool call exceeded its declared timeout; the member keeps its inbox, tasks and membership, and a later wakeup resumes it.
9. Waiting is a captain/owner concern only. A captain may call agent_swarm_wait once with the current Team revision. On no_progress, make one status/task-list check and wake a required inactive member if needed, then end the turn; do not loop. Delegated members never wait: after no-task, submit, or blocker they end their turn and resume only by assignment or wakeup. Repeated same-revision no-progress and three exact consecutive 30/60/120s timeouts are stopped by the wait fuse.
10. Read background Team executions with agent_swarm_list_jobs (kind/status filters, pagination) — every row is one task that entered execution. The job face is read-only: create work as Team tasks and cancel through the Team face, never through the job face.`
