import { useId, useLayoutEffect, useRef } from 'react'
import type { TranslateNS } from '@deepseek-ai/dsh-client-ui-slots'
import type { DirectoryEntry, DirectorySource } from '../rpc/directory-contract.js'
import type { SwarmReadCaptainMemberRowV1 } from '../rpc/read-rpc-contract.js'
import { enumLabel } from './team-dashboard-view-helpers.js'
import { SafePixelAvatar } from './SafePixelAvatar.js'
import { TEAM_DASHBOARD_NS } from './team-dashboard-locales.js'

type T = TranslateNS<typeof TEAM_DASHBOARD_NS>
export type MemberProfileTab = 'attributes' | 'work' | 'capabilities' | 'results'
/** Display adaptation of the existing Host summary; unknown public prose stays literal. */
function retainedHistoryLabel(value: string, t: T): string {
  const match = /^Retained history: (0|[1-9]\d*) accepted (task|tasks) · (0|[1-9]\d*) rejected (attempt|attempts)$/u.exec(value)
  if (match === null || match[0] !== value || match[2] !== (match[1] === '1' ? 'task' : 'tasks') || match[4] !== (match[3] === '1' ? 'attempt' : 'attempts')) return value
  return t('directory.retainedHistory', { accepted: match[1]!, rejected: match[3]! })
}
function Source({ value, t }: { value: DirectorySource; t: T }) {
  const sourceLabel = value.source.startsWith('team-aggregate') ? 'directory.sourceTeam' : value.source.startsWith('team-assignment') ? 'directory.sourceAssignment' : value.source.startsWith('session-') ? 'directory.sourceSession' : value.source.startsWith('scoped-') ? 'directory.sourceRegistry' : 'directory.source'
  return <div className="swarm-profile__source"><small>{t(`directory.${value.state}`)} · {t(sourceLabel)}{value.updatedAt === undefined ? null : <> · <time dateTime={new Date(value.updatedAt).toISOString()} title={new Date(value.updatedAt).toLocaleString()}>{t('directory.updated')}: {new Date(value.updatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></>}</small>
    <details><summary>{t('directory.sourceDetails')}</summary><small>{value.source}{value.version ? ` · ${t('directory.version')}: ${value.version}` : ''}{value.updatedAt === undefined ? '' : ` · ${t('directory.updated')}: ${new Date(value.updatedAt).toLocaleString()}`}{` · ${t('directory.observed')}: ${new Date(value.observedAt).toLocaleString()}`}{value.reason ? ` · ${value.reason}` : ''}</small></details>
  </div>
}

export function MemberProfileContent({ entry, close, result, resultObservedAt, onTask, tab, onTabChange, t }: {
  tab: MemberProfileTab; onTabChange: (tab: MemberProfileTab) => void; entry: DirectoryEntry; close: () => void; result: SwarmReadCaptainMemberRowV1 | undefined; resultObservedAt: number | undefined; onTask?: ((id: string) => void) | undefined; t: T
}) {
  const tabs = ['attributes', 'work', 'capabilities', 'results'] as const
  const id = useId()
  const body = useRef<HTMLDivElement>(null)
  useLayoutEffect(() => { if (body.current) body.current.scrollTop = 0 }, [tab])
  return <section className="swarm-profile__content" data-directory-card={entry.memberId} aria-labelledby={id}>
    <header className="swarm-profile__header">
      <span className="swarm-profile__avatar"><SafePixelAvatar seed={entry.memberId} asset={entry.avatar} name={entry.label} t={t} /></span>
      <div className="swarm-profile__identity"><h3 id={id} title={entry.label} data-profile-heading tabIndex={-1}>{entry.label}</h3><small>{entry.role === 'captain' ? t('captainRole') : t('members')} · {enumLabel(entry.phase, t)}</small><p title={entry.responsibility}>{entry.responsibility || t('directory.unknown')}</p></div>
      <button type="button" aria-label={t('directory.closeProfile')} onClick={close}>×</button>
    </header>
    <div className="swarm-profile__tabs" role="tablist" aria-label={entry.label}>{tabs.map((value, index) => <button type="button" key={value} role="tab" id={`${id}-${value}`} aria-controls={`${id}-panel`} aria-selected={tab === value} tabIndex={tab === value ? 0 : -1} onClick={() => { onTabChange(value) }} onKeyDown={event => {
      const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : undefined
      if (next !== undefined) { event.preventDefault(); onTabChange(tabs[next]!); event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('button')[next]?.focus() }
    }}>{t(`directory.${value}`)}</button>)}</div>
    <div ref={body} className="swarm-profile__body" role="tabpanel" id={`${id}-panel`} aria-labelledby={`${id}-${tab}`} tabIndex={0}>
      {tab === 'attributes' ? <><dl>{(['profession', 'personality', 'biography'] as const).map(key => <div key={key}><dt>{t(`directory.${key}`)}</dt><dd>{entry[key] || t('directory.unknown')}</dd></div>)}</dl><Source value={entry.profile} t={t} /><details><summary>{t('directory.identity')}</summary><code>{entry.name} · {entry.memberId}</code></details></> : null}
      {tab === 'work' ? <section><h4>{t('directory.tasks')}</h4>{entry.currentTasks.length === 0 ? <p>{t('directory.none')}</p> : <ul className="swarm-profile__tasks">{entry.currentTasks.map(task => <li key={task.id}>{onTask ? <button type="button" onClick={() => { onTask(task.id) }}><strong>{task.subject}</strong><small><span title={task.id}>{task.id.slice(0, 8)}</span> · {task.status === 'in_progress' || task.status === 'submitted' || task.status === 'verifying' ? enumLabel(task.status, t) : task.status}</small><span aria-hidden="true">→</span></button> : <><strong>{task.subject}</strong><small><span title={task.id}>{task.id.slice(0, 8)}</span> · {task.status === 'in_progress' || task.status === 'submitted' || task.status === 'verifying' ? enumLabel(task.status, t) : task.status}</small></>}</li>)}</ul>}</section> : null}
      {tab === 'capabilities' ? <>
        <section><h4>{t('directory.model')}</h4><p>{entry.model.provider ?? t('directory.unknown')} / {entry.model.model ?? t('directory.unknown')}</p><p>{t(entry.model.imageInput === 'supported' ? 'directory.supported' : entry.model.imageInput === 'unsupported' ? 'directory.unsupported' : 'directory.imageUnknown')}</p><Source value={entry.model} t={t} /></section>
        <section><h4>{t('directory.skills')}</h4>{(['assigned', 'sessionVisible', 'catalog'] as const).map(kind => <details className="swarm-profile__collection" key={kind}><summary>{t(`directory.${kind}`)} <small>{entry.skills[kind].entries.length} · {t(`directory.${entry.skills[kind].state}`)}</small></summary><Source value={entry.skills[kind]} t={t} />{entry.skills[kind].entries.length === 0 ? <p>{t(entry.skills[kind].state === 'available' ? 'directory.none' : 'directory.unknown')}</p> : <ul>{entry.skills[kind].entries.map(skill => <li key={skill.name}><strong>{skill.name}</strong><p>{skill.description ?? t('directory.unknown')}{skill.descriptionTruncated ? <small> · {t('directory.truncated')}</small> : null}</p></li>)}</ul>}</details>)}</section>
        <section><h4>{t('directory.tools')}</h4><Source value={entry.tools} t={t} />{!entry.tools.complete ? <p>{t('directory.partial')}</p> : null}<details className="swarm-profile__collection"><summary>{t('directory.toolPermissions')} <small>{entry.tools.entries.length}</small></summary><ul>{entry.tools.entries.map(tool => <li key={tool.name}><strong>{tool.name}</strong><p>{t(`directory.${tool.state}`)} · {t('directory.policy')}: {t(`directory.${tool.teamPolicy}`)}</p></li>)}</ul></details></section>
      </> : null}
      {tab === 'results' ? result?.recentOutcome === undefined && result?.growthSummary === undefined ? <p>{t('directory.resultsUnknown')}</p> : <><p>{t('directory.resultScope')}</p>{result.recentOutcome ? <p><span title={result.recentOutcome.taskId}>{result.recentOutcome.taskId.slice(0, 8)}</span> · {enumLabel(result.recentOutcome.phase, t)} · {new Date(result.recentOutcome.at).toLocaleString()}</p> : null}{result.growthSummary ? <p>{retainedHistoryLabel(result.growthSummary, t)}</p> : null}{resultObservedAt === undefined ? null : <details><summary>{t('directory.sourceDetails')}</summary><small>{t('directory.observed')}: {new Date(resultObservedAt).toLocaleString()}</small></details>}</> : null}
    </div>
  </section>
}

export const profileCss = `
.swarm-profile,.swarm-profile *{box-sizing:border-box}.swarm-profile{z-index:1000;width:min(400px,calc(100vw - 24px));max-height:min(640px,calc(100dvh - 24px));display:flex;min-height:0;overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font-size:13px;line-height:1.6;box-shadow:0 12px 40px #0003;overflow-wrap:anywhere}
.swarm-profile button{font:inherit;color:inherit;background:transparent;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;padding:5px 9px;cursor:pointer}.swarm-profile button:focus-visible,.swarm-profile summary:focus-visible,.swarm-profile [tabindex="0"]:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:-2px}.swarm-profile__content{display:flex;flex-direction:column;min-width:0;min-height:0;width:100%;max-height:inherit}.swarm-profile__header{display:flex;align-items:flex-start;gap:10px;padding:14px;flex:none}.swarm-profile__avatar{display:block;flex:0 0 48px;width:48px;height:48px;overflow:hidden;border-radius:9px}.swarm-profile__identity{min-width:0;flex:1}.swarm-profile h3{margin:0;font-size:16px;line-height:1.4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.swarm-profile__header>button{flex:none}.swarm-profile__identity p{margin:4px 0 0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.swarm-profile small,.swarm-profile dt{color:var(--dsw-alias-label-secondary);font-size:11px}.swarm-profile__tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;padding:0 12px;flex:none;border-bottom:1px solid var(--dsw-alias-border-l2)}.swarm-profile__tabs button{border:0;border-radius:0;padding:8px 2px;white-space:nowrap}.swarm-profile__tabs [aria-selected=true]{color:var(--dsw-alias-state-business-primary);box-shadow:inset 0 -2px var(--dsw-alias-state-business-primary)}.swarm-profile__body{padding:14px;overflow:auto;overscroll-behavior:contain;min-height:0;scrollbar-width:thin}.swarm-profile h4{margin:0 0 8px;font-size:13px}.swarm-profile p{margin:5px 0}.swarm-profile dl{margin:0}.swarm-profile dd{margin:3px 0 14px;white-space:pre-wrap}.swarm-profile__body>section+section{margin-top:18px;border-top:1px solid var(--dsw-alias-border-l2);padding-top:14px}.swarm-profile details{margin:8px 0}.swarm-profile summary{cursor:pointer}.swarm-profile__source{margin:8px 0}.swarm-profile__source details{margin:2px 0}.swarm-profile ul{padding-left:18px}.swarm-profile li+li{margin-top:9px}.swarm-profile__tasks{list-style:none;padding:0!important}.swarm-profile__tasks button{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:2px 8px;width:100%;text-align:left}.swarm-profile__tasks button small{grid-column:1}.swarm-profile__tasks button>span{grid-column:2;grid-row:1/3;align-self:center}.swarm-profile-modal{position:fixed!important;inset:auto 0 0!important;transform:none!important;width:100%!important;max-width:none!important;max-height:calc(100dvh - 12px)!important;border-radius:16px 16px 0 0!important;padding:0!important;overflow:hidden!important}.swarm-profile-modal .swarm-profile{width:100%;max-height:min(80dvh,720px);border:0;border-radius:16px 16px 0 0;box-shadow:none}
`
