export const publicChatCss = `
.swarm-public,.swarm-public *{box-sizing:border-box}
.swarm-public{container-type:inline-size;display:flex;flex-direction:column;width:100%;height:100%;min-width:0;min-height:0;overflow:hidden;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);font-size:14px}
.swarm-public button{max-width:100%;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:6px 10px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit;font-size:12px;cursor:pointer}
.swarm-public button:disabled{opacity:.5;cursor:default}.swarm-public button:focus-visible,.swarm-public textarea:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
.swarm-public__header{display:flex;justify-content:space-between;align-items:center;gap:12px;flex:none;padding:12px 16px;border-bottom:1px solid var(--dsw-alias-border-l2)}
.swarm-public__header>div{min-width:0;flex:1}.swarm-public__header h1{margin:0;font-size:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.swarm-public__header p{margin:5px 0 0;font-size:12px;color:var(--dsw-alias-label-secondary);overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.swarm-public__header button{flex-shrink:0}
.swarm-public__goal{font-size:12px;color:var(--dsw-alias-label-secondary);margin-top:4px}.swarm-public__goal summary{cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.swarm-public__goal[open] summary{color:var(--dsw-alias-state-business-primary)}.swarm-public__header .swarm-public__goal p{display:block;max-height:110px;overflow:auto;white-space:pre-wrap;overscroll-behavior:contain}
.swarm-public__messages{flex:1;overscroll-behavior:contain;min-height:0;overflow:auto;overflow-x:hidden;padding:20px;scrollbar-width:thin;scroll-behavior:smooth}.swarm-public__empty{color:var(--dsw-alias-label-secondary);text-align:center;margin:40px 0}
.swarm-public__message{max-width:88%;width:fit-content;margin:0 auto 20px 0;padding:12px 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1);overflow-wrap:anywhere;scroll-margin:20px}.swarm-public__message--operator{margin-left:auto;margin-right:0;background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 7%,var(--dsw-alias-bg-layer-1))}
.swarm-public__meta{display:flex;gap:10px;flex-wrap:wrap;align-items:baseline;font-size:12px}.swarm-public__meta time{font-size:11px;color:var(--dsw-alias-label-secondary)}.swarm-public__text{white-space:pre-wrap;line-height:1.7;margin:8px 0}.swarm-public__message footer{display:flex;justify-content:space-between;gap:12px;align-items:center;color:var(--dsw-alias-label-secondary);font-size:11px}.swarm-public__message footer button{border:0;background:transparent;padding:2px 0}
.swarm-public__quote{display:block;max-width:100%;border-left:2px solid var(--dsw-alias-border-l2);padding:3px 8px;margin:6px 0;font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary)}
.swarm-public__composer{flex:none;min-width:0;padding:12px 20px 16px;border-top:1px solid var(--dsw-alias-border-l2)}.swarm-public__composer p{font-size:12px;overflow-wrap:anywhere}.swarm-public__composer textarea{display:block;width:100%;max-height:160px;min-height:72px;resize:vertical;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:10px 12px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit;line-height:1.6}.swarm-public__send-row{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-top:8px}.swarm-public__send-row small{min-width:0;font-size:11px;color:var(--dsw-alias-label-secondary)}.swarm-public__send-row button{flex:none;background:var(--dsw-alias-state-business-primary);color:white;border:0;padding:7px 16px}
@container(max-width:768px){.swarm-public__header{padding:12px}.swarm-public__messages{padding:12px}.swarm-public__composer{padding:10px 12px}.swarm-public__message{max-width:96%}}

.swarm-public__tokens{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.swarm-public__token{display:inline-flex;align-items:center;max-width:100%;border:1px solid var(--dsw-alias-state-business-primary);border-radius:6px;padding-left:6px;font-size:12px;overflow-wrap:anywhere}.swarm-public__token button{border:0;padding:3px 5px;background:transparent}.swarm-public__token>span{min-width:0}
.swarm-public__composer{max-height:55%;overflow-y:auto;overscroll-behavior:contain}.swarm-public__candidate-box{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;margin-top:6px;padding:4px;max-width:100%}.swarm-public__candidate-box p{margin:4px}.swarm-public__candidates{max-height:160px;overflow:auto}.swarm-public__candidates>button{display:flex;align-items:center;gap:8px;width:100%;text-align:left;border:0}.swarm-public__candidates>button[aria-selected=true]{background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 12%,transparent)}.swarm-public__candidates>button>.swarm-public__candidate-avatar{display:block;flex:0 0 32px;width:32px;height:32px;overflow:hidden}.swarm-public__candidates>button>.swarm-public__candidate-copy{flex:1;min-width:0}.swarm-public__candidates>button>span{display:flex;flex-direction:column;min-width:0;overflow-wrap:anywhere}.swarm-public__candidates small{font-size:11px;color:var(--dsw-alias-label-secondary)}.swarm-public__receipt{display:block;overflow-wrap:anywhere}
`
